### ISSUE TITLE
Small TODO's

### ISSUE THREAD

**Issue by keighrim** [keighrim/cs105_nT#100]
just small todo's for myself

* [x] link team page to "4 students" in README
* [x] delete redis instance of partials when un/follow happens

**Comment by keighrim** [comment]
* [ ] add load test results to README

**Comment by keighrim** [comment]
closed by #105 #106 #108
